import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chorcha Merch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const primaryAccent = "text-cyan-400"; // Neon Cyan
  const secondaryAccent = "text-purple-400"; // Neon Purple
  const bgDark = "bg-gray-900";
  const cardBg = "bg-gray-800";
  const buttonPrimary = "bg-cyan-600 hover:bg-cyan-500 text-gray-900 font-bold";
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Link href={"/caps"}>caps</Link>
        <Link href={"/hoodies"}>hoodies</Link>
        <Link href={"/t-shirts"}>t-shirts</Link> */}
        <header className="sticky top-0 z-50 bg-gray-900/90 backdrop-blur-sm border-b border-purple-500/50">
          <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex justify-between items-center h-16">
            {/* Logo/Brand */}
            <div className="text-2xl font-bold tracking-widest text-purple-400">
              <Link href={"/"}><span className={primaryAccent}>CHORCHA-</span>MERCH</Link>
            </div>

            {/* Navigation Links */}
            <div className="flex space-x-8">
              <Link
                href="/hoodies"
                className={`text-gray-300 hover:${primaryAccent} transition duration-150`}
              >
                HOODIES
              </Link>
              <Link
                href="/t-shirts"
                className={`text-gray-300 hover:${primaryAccent} transition duration-150`}
              >
                T-SHIRTS
              </Link>
              <Link
                href="/caps"
                className={`text-gray-300 hover:${primaryAccent} transition duration-150`}
              >
                CAPS
              </Link>
            </div>

            {/* Action/Icon (e.g., Cart) */}
            <div className="text-xl text-gray-300 hover:text-purple-400 cursor-pointer">
              🛒 {/* Shopping Cart Icon */}
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
